// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:hour/shared/config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Config.apiKeyWeb,
    appId: Config.appIdWeb,
    messagingSenderId: Config.messagingSenderId,
    projectId: Config.projectId,
    authDomain: Config.authDomainWeb,
    storageBucket: Config.storageBucket,
    measurementId: Config.measurementIdWeb,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Config.apiKeyAndroid,
    appId: Config.appIdAndroid,
    messagingSenderId: Config.messagingSenderId,
    projectId: Config.projectId,
    storageBucket: Config.storageBucket,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Config.apiKeyIos,
    appId: Config.appIdIos,
    messagingSenderId: Config.messagingSenderId,
    projectId: Config.projectId,
    storageBucket: Config.storageBucket,
    iosClientId: Config.iosClientId,
    iosBundleId: Config.iosBundleId,
  );
}
